import json
import wikipediaapi
import os
from utils import File, Log, TimeFormat
log = Log('build_wikipedia_data')
ELECTION_LIST = [
      ("Presidential", "2024-10-24"),
      ("Presidential", "2019-11-16"),
      ("Presidential", "2015-01-08"),
      ("Presidential", "2010-01-26"),
      ("Presidential", "2005-11-17"),
      ("Presidential", "1999-12-21"),
      ("Presidential", "1994-11-09"),
      ("Presidential", "1988-12-19"),
      ("Presidential", "1982-10-20"),    
      ("Parliamentary", "2025-08-05"),
      ("Parliamentary", "2020-08-05"),
      ("Parliamentary", "2015-08-17"),
      ("Parliamentary", "2010-04-08"),
      ("Parliamentary", "2004-04-02"),
      ("Parliamentary", "2001-12-05"),
      ("Parliamentary", "2000-10-10"),
      ("Parliamentary", "1994-08-16"),
      ("Parliamentary", "1989-02-15"),
]

def main():
    var_name = 'WIKIPEDIA_SUMMRY_IDX'
    time_id = TimeFormat.TIME_ID.formatNow
    lines = [
        
        '// Autogenerated by build_wikipedia_data.py',
        '// at ' + time_id,
        '',
        f'const {var_name} = ' + '{',
    ]
    for election_type, date_str in ELECTION_LIST:
        year_str = date_str.split('-')[0]
        wiki_page_name = f'{year_str}_Sri_Lankan_{election_type.lower()}_election'
        log.debug(wiki_page_name)
        try:
            wiki = wikipediaapi.Wikipedia("lk_elections", "en")
            page = wiki.page(wiki_page_name)
            summary = page.summary
            lines.extend([
                '',
                '  // ' + wiki_page_name,
                f'  "{wiki_page_name}": {json.dumps(summary)},',
            ])
        except Exception as e:
            log.error(f'Error fetching {wiki_page_name}: {e}')


    lines.extend([
        '',
        '};',
        '',
        f'export default {var_name};',
    ])
    
    data_path = os.path.join('src', 'nonview', 'constants', f'{var_name}.js')
    File(data_path).write_lines(lines)
    log.info(f'Wrote {data_path}')

if __name__ == "__main__":
    main()