def get_party_wiki_page_name_list():
    names = [
        "All Ceylon Tamil Congress",
        "Democratic People's Liberation Front",
        "Eelam People's Democratic Party",
        "Illankai Tamil Arasu Kachchi",
        "Jathika Jana Balawegaya",
        "Janatha Vimukthi Peramuna",
        "Lanka Sama Samaja Party",
        "Mahajana Eksath Peramuna",
        "Muslim National Alliance",
        "New Democratic Front",
        "National Movement for People's Power",
        "National People's Power",
        "National Unity Alliance",
        "People's Alliance",
        "Samagi Jana Balawegaya",
        "Sri Lanka Freedom Party",
        "Sri Lanka Muslim Congress",
        "Sri Lanka Mahajana Pakshaya",
        "Sri Lanka Podujana Peramuna",
        "Tamil Makkal Viduthalai Pulikal",
        "Tamil United Liberation Front",
        "United National Party",
        "United People's Freedom Alliance",
        "Sihala Urumaya",
        "Jathika Hela Urumaya",
        "All Ceylon Makkal Congress",
        "National Congress",
    ]
    return [name.replace(' ', '_') for name in names]
