// Auto-generated by add_indices.py
import AbstractCustomPage from "./AbstractCustomPage";
import BasePage from "./BasePage";
import CountryPage from "./CountryPage";
import ElectionPage from "./ElectionPage";
import ElectionResultPage from "./ElectionResultPage";
import ElectoralDistrictPage from "./ElectoralDistrictPage";
import PollingDivisionPage from "./PollingDivisionPage";

export {
  AbstractCustomPage,
  BasePage,
  CountryPage,
  ElectionPage,
  ElectionResultPage,
  ElectoralDistrictPage,
  PollingDivisionPage,
};
