// Auto-generated by add_indices.py
import AbstractCustomPage from './AbstractCustomPage'
import AnalysisBellwetherPage from './AnalysisBellwetherPage'
import AnalysisFloatingVotePage from './AnalysisFloatingVotePage'
import BasePage from './BasePage'
import CountryPage from './CountryPage'
import ElectionPage from './ElectionPage'
import ElectoralDistrictPage from './ElectoralDistrictPage'
import PartyGroupPage from './PartyGroupPage'
import PartyPage from './PartyPage'
import PollingDivisionPage from './PollingDivisionPage'
import RandomPage from './RandomPage'

export {
  AbstractCustomPage,
  AnalysisBellwetherPage,
  AnalysisFloatingVotePage,
  BasePage,
  CountryPage,
  ElectionPage,
  ElectoralDistrictPage,
  PartyGroupPage,
  PartyPage,
  PollingDivisionPage,
  RandomPage,
}
