// Auto-generated by javascript_version.py
export const DATETIME_STR = "2024-02-20 16:29:50";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
