// Autogenerated by build_wikipedia_data.py
// at 20240416.154656

const WIKIPEDIA_SUMMRY_IDX = {
  // 2024_Sri_Lankan_presidential_election
  "2024_Sri_Lankan_presidential_election":
    "Presidential elections are scheduled to be held in Sri Lanka sometime between September and October 2024, according to the Constitution of Sri Lanka.\nVoters will elect a president for a term of five years.\nIncumbent president Ranil Wickremesinghe is eligible to run for re-election. ",

  // 2019_Sri_Lankan_presidential_election
  "2019_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 16 November 2019.\nThe incumbent President Maithripala Sirisena's term of office would have ended on 9 January 2020.\nThis was the first presidential election in Sri Lanka where no sitting president, prime minister or opposition leader ran for president. \nSajith Premadasa, son of former president Ranasinghe Premadasa and deputy leader of the United National Party was the candidate of the ruling party.\nGotabaya Rajapaksa, brother of former president Mahinda Rajapaksa, was the candidate of the Sri Lanka Podujana Peramuna and was endorsed by the Sri Lanka Freedom Party. The results were announced on 17 November 2019.\nRajapaksa won the election in a landslide victory, defeating his main opponent Premadasa by a significant margin, thus bringing the Rajapaksa family back to power after a 5-year interregnum. ",

  // 2015_Sri_Lankan_presidential_election
  "2015_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 8 January 2015, two years ahead of schedule.\nIncumbent President Mahinda Rajapaksa was the ruling United People's Freedom Alliance's candidate, seeking a third term in office.\nThe United National Party (UNP)-led opposition coalition chose to field Maithripala Sirisena, the former Minister of Health in Rajapaksa's government and general secretary of the Sri Lanka Freedom Party (SLFP) \u2013 the main constituent party of the UPFA \u2013 as its common candidate. Sirisena was declared the winner, receiving 51. 28% of all votes cast compared to Rajapaksa's 47. 58%.\nThe result was generally seen as a major upset; when Rajapaksa called the election in November 2014 he had looked certain to win.\nOn 11 January 2015, the new government announced a special investigation into allegations of an attempted coup by Rajapaksa. ",

  // 2010_Sri_Lankan_presidential_election
  "2010_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 26 January 2010.\nThe elections were announced on 23 November 2009 when incumbent President Mahinda Rajapaksa decided to seek a fresh mandate prior to the expiration of his term in 2011.\nNominations were accepted on 17 December 2009. Rajapaksa, who was elected president for a 6-year term in November 2005, was the candidate of the ruling United People's Freedom Alliance.\nGeneral Sarath Fonseka, a former commander of the Sri Lankan Army, was his main opponent in the election.\nFonseka had been endorsed by a number of main opposition parties, including the United National Party and the Janatha Vimukthi Peramuna. \nPresident Rajapaksa proceeded to win re-election, over 57% of all votes cast.\nFonseka received over 40%, carrying the Northern and Eastern Provinces of Sri Lanka.\nThe remaining twenty candidates all garnered less than 0. 5% of the popular vote. ",

  // 2005_Sri_Lankan_presidential_election
  "2005_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 17 November 2005.\nNominations were accepted on 7 September 2005 and electoral participation was 73. 73%.\nPrime Minister Mahinda Rajapaksa of the governing United People's Freedom Alliance was elected, receiving 50. 3% of all votes cast. ",

  // 1999_Sri_Lankan_presidential_election
  "1999_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 21 December 1999.\nNominations were accepted on 16 November 1999 and electoral participation was 73. 31%.\nIncumbent President Chandrika Kumaratunga of the governing People's Alliance was re-elected for a second term, receiving 51% of all votes cast. ",

  // 1994_Sri_Lankan_presidential_election
  "1994_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 9 November 1994.\nNominations were accepted on 7 October 1994 and electoral participation was 70. 47%.\nPrime Minister Chandrika Kumaratunga of the governing People's Alliance was elected, receiving 62% of all votes cast. ",

  // 1988_Sri_Lankan_presidential_election
  "1988_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka on 19 December 1988.\nNominations were accepted on 10 November 1988.\nPrime Minister Ranasinghe Premadasa of the governing United National Party was elected, receiving 50. 4% of all votes cast.\nVoter turnout was only 55. 32%, substantially lower than the previous election and the lowest turnout for a Sri Lankan presidential election. ",

  // 1982_Sri_Lankan_presidential_election
  "1982_Sri_Lankan_presidential_election":
    "Presidential elections were held in Sri Lanka for the first time on 20 October 1982.\nIncumbent president J.\nR.\nJayewardene of the governing United National Party was elected, receiving 53% of all votes cast. Nominations were accepted on 17 September 1982 and electoral participation was 81. 06%.\nThe election was described as a fight between capitalism and socialism: Hector Kobbekaduwa, who advocated to carry on the policies of the previous SLFP-led regime of Sirimavo Bandaranaike, was expected to undo most of the open market and capitalist reforms brought in by J.\nR.\nJayewardene. Although the SLFP lost, they managed to win a significant number of votes in Tamil-speaking areas in the north. ",

  // 2025_Sri_Lankan_parliamentary_election
  "2025_Sri_Lankan_parliamentary_election":
    "Parliamentary elections are scheduled to be held in Sri Lanka before August 2025 according to the constitution.\nThe president has the power under the constitution to hold elections two and half years after the previous elections, which took place in August 2020. ",

  // 2020_Sri_Lankan_parliamentary_election
  "2020_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 5 August 2020 to elect 225 members to Sri Lanka's 16th Parliament.\n16,263,885 people were eligible to vote in the election, 31. 95% of whom were young voters. The incumbent Sri Lanka People's Freedom Alliance coalition claimed a landslide victory in the election, winning 145 seats, while Samagi Jana Balawegaya won 54 seats, Tamil National Alliance won 10 seats and National People's Power won 3 seats.\nThe main opposition United National Party suffered the worst showing in its history following a split over party leadership, finishing in fourth place with only one seat. The election was postponed at least twice due to a surge in COVID-19 cases in the country, before the date was finalized as 5 August 2020.\nPrior to the election, a coronavirus-proof mock election was conducted by the Election Commission in June 2020 as a trial run in order to comply with health guidelines. Initial reports revealed that the overall voter turnout was estimated at 70%, comparatively less than the turnout of the previous elections, mainly due COVID-19.\nVote counting started on 6 August 2020 at around 9 am.\nThe new parliament is expected to reconvene on 20 August 2020. In November 2018, the date was briefly moved forward by more than a year to 5 January 2019 after President Maithripala Sirisena dissolved parliament during a constitutional crisis and called for a snap election.\nThe Supreme Court later suspended the dissolution and ordered a halt to the snap election, effectively moving the election's date back to 2020. The next general election in Sri Lanka is scheduled to be held in 2025; however, the president has the power to dissolve parliament anytime after 2+1\u20442 years according to the constitution. ",

  // 2015_Sri_Lankan_parliamentary_election
  "2015_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 17 August 2015, ten months ahead of schedule, to elect 225 members to Sri Lanka's 15th Parliament. The United National Party (UNP) led United National Front for Good Governance (UNFGG) won 106 seats, an increase of 46 since the 2010 election, but failed to secure a majority in Parliament.\nThe United People's Freedom Alliance (UPFA) won 95 seats, a decline of 49.\nThe Tamil National Alliance (TNA), the largest party representing Sri Lankan Tamils, won 16 seats, an increase of two from 2010.\nThe remaining eight seats were won by Janatha Vimukthi Peramuna (6), Sri Lanka Muslim Congress (1) and Eelam People's Democratic Party (1).\nPrime Minister Ranil Wickremesinghe, leader of the UNFGG and UNP, was able to form a national government with the support of UPFA MPs loyal to President Maithripala Sirisena. ",

  // 2010_Sri_Lankan_parliamentary_election
  "2010_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 8 and 20 April 2010, to elect 225 members to Sri Lanka's 14th Parliament.\n14,088,500 Sri Lankans were eligible to vote in the election at 11,102 polling stations.\nIt was the first general election to be held in Sri Lanka following the conclusion of the civil war which lasted 26 years. \nThe main parties contesting in the election were the ruling United People's Freedom Alliance (UPFA), the main opposition United National Front (UNF) and the Democratic National Alliance (DNA) led by former commander of the Sri Lankan Army Sarath Fonseka.\nPresident Mahinda Rajapaksa had previously been reelected as president in January 2010. \nAs expected, the UPFA secured a landslide victory in the elections, buoyed by its achievement of ending the 30 year Sri Lankan Civil War and defeating the Liberation Tigers of Tamil Eelam in May 2009.\nThe UPFA won a large majority in the parliament, obtaining 144 seats, an increase of 39 since the 2004 election.\nThe main opposition UNF won 60 seats, a decline of 22.\nThe minority Tamil party Tamil National Alliance (TNA) won 14 seats, down from the 22 they won in 2004, and the DNA, contesting for the first time, won 7 seats.\nThe UPFA however fell short of its goal of obtaining a two-thirds supermajority in the house, which it would have needed to change the constitution on its own.\nThe election had the lowest voter turnout in Sri Lanka since independence. While the elections were initially scheduled to be concluded on 8 April, irregularities in two districts led the Commissioner of Elections to hold re-polls on 20 April.\nFinal results were announced the following day, a day before the new parliament was scheduled to meet for the first time. ",

  // 2004_Sri_Lankan_parliamentary_election
  "2004_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 2 April 2004.\nThe ruling United National Party of Prime Minister Ranil Wickremesinghe was defeated, winning only eighty two seats in the 225-member Sri Lankan parliament.\nThe opposition United People's Freedom Alliance won 105 seats.\nWhile this was eight seats short of an absolute majority, the Alliance was able to form a government. \nOn 6 April, President Chandrika Kumaratunga appointed former Minister of Labour Mahinda Rajapaksa as Prime Minister. ",

  // 2001_Sri_Lankan_parliamentary_election
  "2001_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 5 December 2001, just a little over a year after the previous elections in October 2000. ",

  // 2000_Sri_Lankan_parliamentary_election
  "2000_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 10 October 2000. \nThe People's Alliance (PA) government Kumaratunga had led for six years was facing increasing criticism on two fronts: a series of military defeats at the hands of the rebel Liberation Tigers of Tamil Eelam in the country's civil war, and the faltering performance of the economy. \nThe elections were marred by violence.\n Seventy people were killed during the campaign, including six on election day itself.\n [1].\n Both the UNP and SLMC parties accused the PA of election fraud and intimidation. \nAs was the case for most elections since 1983, few ballots were cast in LTTE-held parts of the country. ",

  // 1994_Sri_Lankan_parliamentary_election
  "1994_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 16 August 1994.\nThey marked the decisive end of seventeen years of United National Party rule and a revival of Sri Lankan democracy. ",

  // 1989_Sri_Lankan_parliamentary_election
  "1989_Sri_Lankan_parliamentary_election":
    "Parliamentary elections were held in Sri Lanka on 15 February 1989, the first since 1977.\n The elections that should normally have been held by 1983 had been cancelled by the 1982 referendum. ",
};

export default WIKIPEDIA_SUMMRY_IDX;
